# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'clover_dashboard.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QPushButton, QSizePolicy,
    QWidget)
import Resources_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(930, 500)
        self.DashboardScreen = QWidget(Dialog)
        self.DashboardScreen.setObjectName(u"DashboardScreen")
        self.DashboardScreen.setGeometry(QRect(0, 0, 930, 501))
        self.DashboardScreen.setStyleSheet(u"#cbody{background-color:#000}")
        self.cbody = QLabel(self.DashboardScreen)
        self.cbody.setObjectName(u"cbody")
        self.cbody.setGeometry(QRect(270, 0, 360, 501))
        self.rsbody = QLabel(self.DashboardScreen)
        self.rsbody.setObjectName(u"rsbody")
        self.rsbody.setGeometry(QRect(630, 0, 300, 500))
        self.rsbody.setStyleSheet(u"#rsbody{background-color:#121212}")
        self.usrnm = QLabel(self.DashboardScreen)
        self.usrnm.setObjectName(u"usrnm")
        self.usrnm.setGeometry(QRect(15, 77, 181, 41))
        self.usrnm.setStyleSheet(u"#usrnm{color: #FFFFFF; font-size: 30px;}")
        self.dashboard_text = QLabel(self.DashboardScreen)
        self.dashboard_text.setObjectName(u"dashboard_text")
        self.dashboard_text.setGeometry(QRect(10, 10, 261, 50))
        self.dashboard_text.setStyleSheet(u"#dashboard_text{color: #FFFFFF; font-size: 48px; font-weight: 500;}")
        self.pwdlabel = QLabel(self.DashboardScreen)
        self.pwdlabel.setObjectName(u"pwdlabel")
        self.pwdlabel.setGeometry(QRect(297, 9, 281, 51))
        self.pwdlabel.setStyleSheet(u"#pwdlabel{color: #FFF; font-size: 48px; font-weight: 500;}")
        self.removebtn = QPushButton(self.DashboardScreen)
        self.removebtn.setObjectName(u"removebtn")
        self.removebtn.setGeometry(QRect(560, 9, 48, 48))
        self.removebtn.setStyleSheet(u"#removebtn{background-color: #00000000;}")
        icon = QIcon()
        icon.addFile(u":/Icons/rsrc/remove_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.removebtn.setIcon(icon)
        self.removebtn.setIconSize(QSize(40, 40))
        self.applist = QListWidget(self.DashboardScreen)
        self.applist.setObjectName(u"applist")
        self.applist.setGeometry(QRect(294, 66, 312, 424))
        self.applist.setStyleSheet(u"")
        self.emailid = QLabel(self.DashboardScreen)
        self.emailid.setObjectName(u"emailid")
        self.emailid.setGeometry(QRect(655, 260, 250, 45))
        self.emailid.setStyleSheet(u"#appname{background-color:#2A2A2A;  }")
        self.appfield = QLineEdit(self.DashboardScreen)
        self.appfield.setObjectName(u"appfield")
        self.appfield.setGeometry(QRect(648, 30, 264, 40))
        self.appfield.setStyleSheet(u"#appfield{font-size: 48px; font-weight: 200; font-size:25px; }")
        self.emailfield = QLineEdit(self.DashboardScreen)
        self.emailfield.setObjectName(u"emailfield")
        self.emailfield.setGeometry(QRect(648, 81, 264, 40))
        self.emailfield.setStyleSheet(u"#emailfield{font-size: 48px; font-weight: 200; font-size:25px; }")
        self.generatepwd = QPushButton(self.DashboardScreen)
        self.generatepwd.setObjectName(u"generatepwd")
        self.generatepwd.setGeometry(QRect(660, 380, 240, 50))
        self.appname = QLabel(self.DashboardScreen)
        self.appname.setObjectName(u"appname")
        self.appname.setGeometry(QRect(655, 205, 250, 45))
        self.appname.setStyleSheet(u"#emailid{background-color:#2A2A2A ; }")
        self.copypwd = QPushButton(self.DashboardScreen)
        self.copypwd.setObjectName(u"copypwd")
        self.copypwd.setGeometry(QRect(660, 320, 240, 50))
        self.lsibody2 = QLabel(self.DashboardScreen)
        self.lsibody2.setObjectName(u"lsibody2")
        self.lsibody2.setGeometry(QRect(0, 90, 270, 431))
        self.lsibody2.setStyleSheet(u"#lsibody2{background-color:#212121;}")
        self.lsbody = QLabel(self.DashboardScreen)
        self.lsbody.setObjectName(u"lsbody")
        self.lsbody.setGeometry(QRect(0, 0, 270, 70))
        self.lsbody.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0.72897, y1:0.278227, x2:0, y2:0.983, stop:0 rgba(0, 25, 52, 255), stop:1 rgba(0, 0, 0, 255));")
        self.rsibody = QLabel(self.DashboardScreen)
        self.rsibody.setObjectName(u"rsibody")
        self.rsibody.setGeometry(QRect(640, 189, 280, 251))
        self.rsibody.setStyleSheet(u"#rsibody{background-color:#1A1A1A; border-radius: 20;}")
        self.alertbox = QLabel(self.DashboardScreen)
        self.alertbox.setObjectName(u"alertbox")
        self.alertbox.setGeometry(QRect(655, 450, 250, 35))
        self.alertbox.setStyleSheet(u"")
        self.rsibody2 = QLabel(self.DashboardScreen)
        self.rsibody2.setObjectName(u"rsibody2")
        self.rsibody2.setGeometry(QRect(640, 15, 280, 291))
        self.rsibody2.setStyleSheet(u"#rsibody2{background-color:#2A2A2A; border-radius: 20;}")
        self.addbtn = QPushButton(self.DashboardScreen)
        self.addbtn.setObjectName(u"addbtn")
        self.addbtn.setGeometry(QRect(660, 130, 240, 50))
        self.logoutbtn = QPushButton(self.DashboardScreen)
        self.logoutbtn.setObjectName(u"logoutbtn")
        self.logoutbtn.setGeometry(QRect(210, 78, 41, 36))
        self.usrnm_ = QLabel(self.DashboardScreen)
        self.usrnm_.setObjectName(u"usrnm_")
        self.usrnm_.setGeometry(QRect(0, 52, 270, 71))
        self.usrnm_.setStyleSheet(u"#usrnm_{background-color:#1A1A1A; border-radius:20}")
        self.lsibody2.raise_()
        self.usrnm_.raise_()
        self.lsbody.raise_()
        self.rsbody.raise_()
        self.rsibody2.raise_()
        self.rsibody.raise_()
        self.cbody.raise_()
        self.applist.raise_()
        self.usrnm.raise_()
        self.pwdlabel.raise_()
        self.removebtn.raise_()
        self.appfield.raise_()
        self.emailfield.raise_()
        self.generatepwd.raise_()
        self.copypwd.raise_()
        self.alertbox.raise_()
        self.appname.raise_()
        self.emailid.raise_()
        self.addbtn.raise_()
        self.logoutbtn.raise_()
        self.dashboard_text.raise_()

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Clover | Dashboard", None))
        self.cbody.setText("")
        self.rsbody.setText("")
        self.usrnm.setText(QCoreApplication.translate("Dialog", u"usrnm", None))
        self.dashboard_text.setText(QCoreApplication.translate("Dialog", u"dashboard", None))
        self.pwdlabel.setText(QCoreApplication.translate("Dialog", u"Passwords", None))
#if QT_CONFIG(whatsthis)
        self.removebtn.setWhatsThis(QCoreApplication.translate("Dialog", u"Logout", None))
#endif // QT_CONFIG(whatsthis)
        self.removebtn.setText("")
        self.emailid.setText("")
        self.appfield.setPlaceholderText(QCoreApplication.translate("Dialog", u"Enter App Name", None))
        self.emailfield.setPlaceholderText(QCoreApplication.translate("Dialog", u"Enter Email ", None))
        self.generatepwd.setText(QCoreApplication.translate("Dialog", u"ReGenerate Password", None))
        self.appname.setText("")
        self.copypwd.setText(QCoreApplication.translate("Dialog", u"Click to Copy Password", None))
        self.lsibody2.setText("")
        self.lsbody.setText("")
        self.rsibody.setText("")
        self.alertbox.setText("")
        self.rsibody2.setText("")
        self.addbtn.setText("")
        self.logoutbtn.setText("")
        self.usrnm_.setText("")
    # retranslateUi

